import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import NavBarPage from "@/layout/navbar/navbar";
import FooterPage from "@/layout/footer/footer";



const mali = localFont({
  src: "../../public/font/Mali-Regular.ttf",
  variable: "--font-tcs4",
  weight: "400",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mali.className} antialiased flex flex-col min-h-screen`}
      >
        <NavBarPage></NavBarPage>
        {children}
        <FooterPage></FooterPage>
      </body>
    </html>
  );
}
